version: '3.8'
services:
    mysql:
        image: mysql:8.0
        container_name: openpos_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: openpos
            MYSQL_USER: openpos
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootsecret
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./mysql-init:/docker-entrypoint-initdb.d
        command: --default-authentication-plugin=mysql_native_password

volumes:
    mysql_data:
